name = "megaverse-universe"

[build]
command = "pnpm install --no-frozen-lockfile && pnpm run build"
output_dir = ".vercel/output/static"

[build.environment]
NODE_VERSION = "18.17.1"
PNPM_VERSION = "8.7.1"
