name = "megaverse-universe"

compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm install && pnpm run build"

[build.upload]
format = "modules"

[site]
bucket = ".vercel/output/static"

[env.production]
NODE_ENV = "production"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]
