name = "megaverse-universe"

compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm install && pnpm run pages:build"

[build.upload]
format = "modules"

[site]
bucket = ".vercel/output/static"

[env.production]
NODE_ENV = "production"

[pages]
pages_build_output_dir = ".vercel/output/static"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]
