name = "megaverse-universe"

[build]
command = "pnpm install && pnpm run build"
output_dir = ".vercel/output/static"

[build.environment]
NODE_VERSION = "18"
PNPM_VERSION = "8.7.1"

# Add these compatibility flags
[compatibility_flags]
nodejs_compat = true

# Configure build processing
[build.processing]
skip_source_maps = true

# Configure Pages
[pages]
fallback_service_worker = true

# Configure site
[site]
bucket = ".vercel/output/static"
