name = "megaverse-universe"

[build]
command = "pnpm install && pnpm run build"

[build.environment]
NODE_VERSION = "18.17.1"
PNPM_VERSION = "8.7.1"

[build.processing]
skip_source_maps = true

[site]
bucket = ".vercel/output/static"

[env.production]
NODE_ENV = "production"

# Add these compatibility flags
[compatibility_flags]
nodejs_compat = true

# Add specific build output configuration
[build.upload]
format = "service-worker"
